/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AplikasiPenjualanBuku;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author User
 */
public class Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Transaksi
     */
    public Transaksi() throws SQLException {
        initComponents();
         setLocationRelativeTo(this);
        load_date();
        IDOtomatis();
    }
public void load_date() throws SQLException{
   
       
            Connection kon = koneksi.koneksiDb();
            Object header []={"ID BUKU", "JUDUL BUKU", "PENERBIT", "HARGA"};
            DefaultTableModel data=new DefaultTableModel(null, header);
            TbTransaksi.setModel(data);
            String sql_data="SELECT * FROM buku";
            try
           {
                
             
                Statement st=kon.createStatement();
                ResultSet rs=st.executeQuery(sql_data);
                while (rs.next())
                {
                String d1=rs.getString(1);
                String d2=rs.getString(2);
                String d3=rs.getString(3);
                String d4=rs.getString(4);
         
                String d[]={d1, d2, d3, d4};
                data.addRow(d);
                }

            }
            catch(Exception e)
            { 
                JOptionPane.showMessageDialog(null, e);
            }           
}     public void IDOtomatis() {
    try {
        Connection kon = koneksi.koneksiDb();
        Statement st = kon.createStatement();

        String sql_id = "SELECT MAX(id_buku) FROM buku "; // Mengambil nilai maksimum dari ID buku
        ResultSet rs = st.executeQuery(sql_id);
        if (rs.next()) {
            String id_buku = rs.getString(1); // Mengambil nilai ID buku maksimum
            if (id_buku != null) {
                int idNumber = Integer.parseInt(id_buku.substring(1)) + 1;
                String AN = String.format("%05d", idNumber); // Format ID buku dengan 5 digit
                
            } else {
               
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }


}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel2 = new javax.swing.JPanel();
        TTOTAL = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbTransaksi = new javax.swing.JTable();
        clearBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        IDt = new javax.swing.JTextField();
        JM = new javax.swing.JTextField();
        nmPembeli = new javax.swing.JTextField();
        JKalender = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        totalBTN = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TTOTAL.setBackground(new java.awt.Color(204, 255, 255));
        TTOTAL.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        TTOTAL.setEnabled(false);
        jPanel2.add(TTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 170, 40));

        TbTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID BUKU", "HARGA", "JUMLAH", "TOTAL"
            }
        ));
        TbTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbTransaksi);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 480, 180));

        clearBTN.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        clearBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Clear.png"))); // NOI18N
        clearBTN.setText("CLEAR");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });
        jPanel2.add(clearBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 120, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("HARGA");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 60, 20));

        txtHarga.setBackground(new java.awt.Color(204, 255, 255));
        txtHarga.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtHarga.setEnabled(false);
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        jPanel2.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 70, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("TANGGAL");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("NAMA ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("JUMLAH");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel9.setText("ID TRANSAKSI");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 20));
        jPanel2.add(IDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 70, 30));

        JM.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jPanel2.add(JM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 70, 30));

        nmPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmPembeliActionPerformed(evt);
            }
        });
        jPanel2.add(nmPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 130, 30));
        jPanel2.add(JKalender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 150, 30));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save-48.png"))); // NOI18N
        jButton3.setText("SIMPAN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 160, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kembali.png"))); // NOI18N
        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/CETAK.png"))); // NOI18N
        jButton2.setText("Cetak");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        totalBTN.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        totalBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/total.png"))); // NOI18N
        totalBTN.setText("TOTAL");
        totalBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBTNActionPerformed(evt);
            }
        });
        jPanel2.add(totalBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pembelian.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 570, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TbTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbTransaksiMouseClicked
      int selectedRow = TbTransaksi.getSelectedRow();

// Pemeriksaan apakah baris yang dipilih valid
if (selectedRow >= 0 && selectedRow < TbTransaksi.getRowCount()) {
    // Pastikan bahwa kolom yang Anda akses ada dalam batas indeks yang valid
    int hargaColumnIndex = 3;
    int jumlahColumnIndex = 4;
    int totalColumnIndex = 5;

    if (hargaColumnIndex < TbTransaksi.getColumnCount()) {
        txtHarga.setText(TbTransaksi.getModel().getValueAt(selectedRow, hargaColumnIndex).toString());
    }

    if (jumlahColumnIndex < TbTransaksi.getColumnCount()) {
        JM.setText(TbTransaksi.getModel().getValueAt(selectedRow, jumlahColumnIndex).toString());
    }

    if (totalColumnIndex < TbTransaksi.getColumnCount()) {
        TTOTAL.setText(TbTransaksi.getModel().getValueAt(selectedRow, totalColumnIndex).toString());
    }
} else {
    // Tindakan yang sesuai jika baris yang dipilih tidak valid
    // Misalnya, menampilkan pesan kesalahan atau melakukan tindakan lainnya.
}
       
    }//GEN-LAST:event_TbTransaksiMouseClicked

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        IDt.setText("");
        nmPembeli.setText("");
        JKalender.setDate(null);
        txtHarga.setText("");
        JM.setText("");
        TTOTAL.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_clearBTNActionPerformed

    private void totalBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBTNActionPerformed
        if(JM.getText().equals("") || txtHarga.getText().equals("")){
            //Input Tidak Boleh Kosong
            JOptionPane.showMessageDialog(null, "Input Tidak Boleh Kosong");
        }else {
            int jumlah = Integer.valueOf(JM.getText());
            int harga = Integer.parseInt(txtHarga.getText());

            int hasil = jumlah * harga;

            TTOTAL.setText(Integer.toString(hasil));
    }//GEN-LAST:event_totalBTNActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    new Utama().show();
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            try {
            // Path ke file laporan JasperReport
            String reportPath = "src/Report/LaporanTransaksi.jasper";

            // Membuka koneksi ke database MySQL
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/buku", "root", "");

            // Membuat objek HashMap untuk menyimpan parameter yang akan digunakan dalam laporan
            HashMap<String, Object> parameters = new HashMap<>();

            // Mengisi dan menampilkan laporan menggunakan JasperReports
            JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);

            // Membuat objek JasperViewer untuk menampilkan laporan
            JasperViewer viewer = new JasperViewer(print, false);

            // Menampilkan viewer laporan
            viewer.setVisible(true);
        } catch (Exception e) {
            // Menangani kesalahan yang mungkin terjadi saat menampilkan laporan
            JOptionPane.showMessageDialog(this, "Error displaying report: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   // Assuming JKalender is a date picker component
// Mengambil nilai dari JTextField atau komponen lainnya yang sesuai
String Nama_pembeli = nmPembeli.getText();
String harga = txtHarga.getText();
int jumlah = Integer.parseInt(JM.getText());
String total = TTOTAL.getText();

// Mengambil nilai tanggal
Date selectedDate = JKalender.getDate();
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
String formattedDate = sdf.format(selectedDate);

try {
    Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/buku", "root", "");

    String sql = "INSERT INTO transaksi (id_transaksi, Nama_pembeli, tanggal, harga, jumlah, total) VALUES (NULL, ?, ?, ?, ?, ?)";
    try (PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
        preparedStatement.setString(1, Nama_pembeli);
        preparedStatement.setString(2, formattedDate);
        preparedStatement.setString(3, harga);
        preparedStatement.setInt(4, jumlah);
        preparedStatement.setString(5, total);

        int affectedRows = preparedStatement.executeUpdate();
        if (affectedRows > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan.");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data.");
        }
    }

    connection.close();
} catch (SQLException ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
}




    }//GEN-LAST:event_jButton3ActionPerformed

    private void nmPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmPembeliActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Transaksi().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDt;
    private com.toedter.calendar.JDateChooser JKalender;
    private javax.swing.JTextField JM;
    private javax.swing.JTextField TTOTAL;
    private javax.swing.JTable TbTransaksi;
    private javax.swing.JButton clearBTN;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nmPembeli;
    private javax.swing.JButton totalBTN;
    private javax.swing.JTextField txtHarga;
    // End of variables declaration//GEN-END:variables

    private void ViewData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


}
